### ISSUE TITLE
Error while getting certificate

### ISSUE THREAD

**Issue by tbnobody** [moepman/acertmgr#14]
Followed your readme but if I call acertmgr.py I get the following error message:

```
Reading account key...
Traceback (most recent call last):
  File "./acertmgr.py", line 223, in <module>
    cert_get(domains, config)
  File "./acertmgr.py", line 103, in cert_get
    acertmgr_ssl.register_account(acc_key, settings['authority'])
  File "/opt/acertmgr/acertmgr_ssl.py", line 93, in register_account
    "agreement": "https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf",
  File "/opt/acertmgr/acertmgr_ssl.py", line 122, in send_signed
    out = crypto.sign(account_key, '.'.join([protected64, payload64]), 'sha256')
  File "/usr/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 2092, in sign
    _lib.EVP_SignUpdate(md_ctx, data, len(data))
TypeError: initializer for ctype 'void *' must be a cdata pointer, not unicode

```

System is a Debian Jessie. With Python 2.7.9. The required dependencies where installed using apt.

**Comment by tbnobody** [comment]
Btw. same issue with Python 3.4

**Comment by moepman** [comment]
What is your version of python-openssl?
It must be at least 0.15.1 as documented in README.md.

**Comment by tbnobody** [comment]
Grml. You are right... it's 0.14...

**Comment by tbnobody** [comment]
Seems to work with python-openssl from debian-backports
