### ISSUE TITLE
AttributeError: 'unicode' object has no attribute 'get'

### ISSUE THREAD

**Issue by Sprinterfreak** [moepman/acertmgr#38]
https://github.com/moepman/acertmgr/blob/1f5ef9322b260521b26f7a416256244e86323940/acertmgr/authority/v2.py#L211

Just happend after deleting the challenge from the challenge domain caused by a timeout I guess. It didn't printed that it has found the challenge on the verify server because the domain provider is a mess.

```
Error: Certificate issue/renew failed
       Traceback (most recent call last):
         File "/usr/local/lib/python2.7/dist-packages/acertmgr/__init__.py", line 151, in main
           cert_get(config)
         File "/usr/local/lib/python2.7/dist-packages/acertmgr/__init__.py", line 57, in cert_get
           crt, ca = acme.get_crt_from_csr(cr, settings['domainlist'], challenge_handlers)
         File "/usr/local/lib/python2.7/dist-packages/acertmgr/authority/v2.py", line 211, in get_crt_from_csr
           if challenge_status.get('status') == "valid":
       AttributeError: 'unicode' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/bin/acertmgr", line 11, in <module>
    load_entry_point('acertmgr==0.9.6rc1', 'console_scripts', 'acertmgr')()
  File "/usr/local/lib/python2.7/dist-packages/acertmgr/__init__.py", line 210, in main
    raise RuntimeError("{} exception(s) occurred during processing".format(len(exceptions)))
RuntimeError: 1 exception(s) occurred during processing
```

**Comment by Kishi85** [comment]
After some review and being able to reproduce the error code from previous API call is currently not handled correctly and fails with the given error instead of the real error. This is fixed in a191676c89e3b2039027881b2e97f272a59c1d7f
